version: '2'
services:
  app:
    build: .
    ports:
      - "3010:3010"
    depends_on:
      - mongo
      - rabbit
    links:
      - mongo:mongo
      - rabbit:rabbit
    environment:
      SYNCPIPES_PORT: 3010
      SYNCPIPES_MONGO_URL: 'mongodb://mongo/syncpipes'
      SYNCPIPES_RABBIT_HOST: rabbit
      SYNCPIPES_RABBIT_PORT: 5672
      SYNCPIPES_RABBIT_USER: syncpipes
      SYNCPIPES_RABBIT_PASSWORD: p44H3agjpM
      SYNCPIPES_RABBIT_VHOST: '/'
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  rabbit:
    image: rabbitmq:management
    ports:
      - "15672:15672" # management gui
    environment:
      RABBITMQ_DEFAULT_USER: syncpipes
      RABBITMQ_DEFAULT_PASS: p44H3agjpM


